config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'
  resources :password_resets, only: %i[new create edit update]
  resources :users, only: %i[new create show]
  resource :profile, only: %i[show edit update]
  resources :requests
  resources :quests, only: [:show] do
    member do
      get :choice
      post :answer
      get :hint
      get :correct
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  skip_before_action :require_login, only: %i[show choice answer correct hint]
  before_action :set_quest, only: %i[show choice answer correct hint]

  def show; end

  def choice; end

  def answer
    user_input = params[:name]&.strip
    selected_choice = params[:selected_choice]&.strip
    # ユーザー入力が存在するか、選択された選択肢が存在するかを確認
    answer = user_input.presence || selected_choice
    # 正解を判定する条件
    correct_answer = @quest.name.strip
    if answer.present? && correct_answer == answer
      # 正解の場合の処理
      redirect_to correct_quest_path(@quest), notice: "正解です！おめでとうございます！"
    else
      # 不正解または入力がない場合の処理
      redirect_to hint_quest_path(@quest), alert: "残念、不正解です。手がかりをヒントにもう一度挑戦しよう！"
    end
  end

  def correct; end

  def hint; end

  private

  def set_quest
    @quest = Request.find(params[:id])
  end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_caution_note.html.erb
<p class="text-xs text-ash mx-2">
  この物語はAIによって創造されたフィクションであり、実際の人物・団体・事件とは一切関係ありません。
  作中には不自然な表現や想定外の言葉が含まれる可能性がありますので、ご了承ください。
</p>

app/views/quests/_epilogue.html.erb
<div class="mt-8 sm:text-lg overflow-auto">
  私はノートを閉じ、<span class="text-accent"><%= user_name %></span>が戻ってくるのを静かに待った。心の中で、<span class="text-accent"><%= user_name %></span>の隠された才能に驚きつつ、こんなにも素晴らしい作品を他の誰かと共有したいという衝動に駆られたが、それは<span class="text-accent"><%= user_name %></span>の個人的な記録であり、私が勝手に触れるべきではない。<br>
  しばらくして<span class="text-accent"><%= user_name %></span>が席に戻ってくると、何事もなかったかのように会話を再開した。<br>
  しかし、私の心の中には、<span class="text-accent"><%= user_name %></span>の書いた詩が静かに響き続けていた。<br>
  それは、私たちの友情に新たな一面を加え、<span class="text-accent"><%= user_name %></span>をより深く理解するきっかけとなったのだった──。<br>
</div>

app/views/quests/_story1.html.erb
<div class="mt-8 sm:text-lg overflow-auto">
  喫茶店の窓際で、柔らかな陽光がテーブルを照らしている。<br>
  私と<span class="text-accent"><%= user_name %></span>は、お気に入りのコーヒーショップで午後のひと時を楽しんでいた。
  私たちの間には、会話が途切れることなく、温かいコーヒーのカップが並んでいる。<br>
  何気ない日常が穏やかに過ぎていく。<br>
  しかし、その平和なひと時は、突然の出来事によって少しだけ変わり始めた。<br>
  <span class="text-accent"><%= user_name %></span>が席を立っていた時、通りすがりの見知らぬ客が、
  不注意にも<span class="text-accent"><%= user_name %></span>のノートを床に落としてしまったのだ。
  私は慌ててノートを拾い上げた。その時、うっかりとページがめくれてしまい、
  ノートの中身が目に飛び込んできた。そこには、<span class="text-accent"><%= user_name %></span>が心を込めて綴った詩が記されていた──。
</div>

app/views/quests/_story2.html.erb
<div class="mt-4 sm:text-lg overflow-auto">
  文字からは、普段見せない<span class="text-accent"><%= user_name %></span>の深い感情が伝わってきた。
  まるで<span class="text-accent"><%= user_name %></span>の魂が叫んでいるかのようだ。繊細な言葉選びとリズムが、静かに、しかし確かに私の心に響きわたる。
  <span class="text-accent"><%= user_name %></span>が本当に求めているものが、突然として明らかになった瞬間だった。<br>
  そうか、<span class="text-accent"><%= user_name %></span>が今、心から求めているのは──。<br>
</div>

app/views/quests/choice.html.erb
<div class="my-10 mx-auto w-11/12 sm:w-6/5 max-w-3xl">
  <div class="card w-full bg-base-100 image-full shadow-xl">
    <figure><%= image_tag 'note.webp', alt: 'ノートを読む' %></figure>
    <div class="card-body">
      <h2 class="card-title justify-center text-4xl font-moti">- Story2 -</h2>
        <div class="card w-full mx-auto bg-base-200 shadow-xl mt-4">
          <div class="flex flex-col md:flex-row items-center">
            <figure>
              <%= image_tag 'note.png', alt: 'Note', class: 'px-8 pt-8 md:pr-0 md:py-8' %>
            </figure>
            <div class="card-body items-center text-left text-neutral font-poem">
              <h2 class="card-title"><%= @quest.title %></h2>
              <p class="text-sm"><%= @quest.quest %></p>
            </div>
          </div>
        </div>

      <%= render 'story2', user_name: @quest.user.name %>

      <!-- モーダル -->
      <div class="flex justify-center">
        <button class="btn btn-primary w-3/5 mt-4" onclick="my_modal_4.showModal()">なるほど、求めているものはこれだ！</button>
        <dialog id="my_modal_4" class="modal">
          <div class="modal-box relative"> <!-- relativeクラスを追加 -->
            <!-- ✕ボタン -->
            <form method="dialog">
              <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
            </form>
            <!-- モーダルのタイトル -->
            <h3 class="font-bold text-lg text-neutral-400">答えを入力してね！</h3>
            <!-- 回答入力フォーム -->
            <%= form_tag(answer_quest_path(@quest), method: :post, class: "flex flex-col items-center justify-center gap-4 mt-4") do %>
              <div class="w-full max-w-md">
                <div class="form-control w-full">
                  <%= text_field_tag :name, nil, placeholder: "例：クマのぬいぐるみ", class: "input input-bordered", required: true %>
                </div>
                <div class="w-full flex justify-center">
                  <%= submit_tag "送信", class: "btn hover:bg-primary hover:border-primary mt-4" %>
                </div>
              </div>
              <p class="text-xs text-neutral-400">※正確に入力してください(漢字,カタカナ、スペース等)</p>
            <% end %>
          </div>
        </dialog>
      </div>

      <div class="card-actions justify-center mt-2">
        <%= link_to 'まだ分からないな。もう少し手がかりを探そう', hint_quest_path(@quest), class: "btn btn-primary w-3/5" %>
      </div>
    </div>
  </div>
  <%= render 'caution_note' %>
</div>

app/views/quests/correct.html.erb
<div class="my-10 mx-auto w-11/12 sm:w-6/5 max-w-3xl">
  <div class="card w-full bg-base-100 image-full shadow-xl">
    <figure><%= image_tag 'wait.webp', alt: '友人を待つ' %></figure>
    <div class="card-body">
      <h2 class="card-title justify-center text-4xl font-moti">- Epilogue -</h2>

      <%= render 'epilogue', user_name: @quest.user.name %>

      <div class="flex justify-center mt-8 md:mt-16">
        <!-- モーダル -->
        <button class="btn btn-primary" onclick="my_modal_5.showModal()">リクエスト詳細</button>
        <dialog id="my_modal_5" class="modal">
          <div class="modal-box relative"> <!-- relativeクラスを追加 -->
            <!-- ✕ボタン -->
            <form method="dialog">
              <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
            </form>
            <!-- クエスト詳細 -->
            <section class="text-ash body-font">
              <div class="container px-8 p-4 pb-8 mx-auto">
                <p class="text-ash mb-10 p-1 bg-gradient-to-r from-green-200 to-indigo-200 font-bold text-center rounded-full">リクエスト内容</p>
                <div class="-my-8 divide-y-4 divide-green-200 divide-dotted">
                  <div class="py-4 flex flex-wrap md:flex-nowrap">
                    <div class="md:w-48 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                      <span class="font-semibold title-font">欲しいもの</span>
                    </div>
                    <div class="md:flex-grow w-full">
                      <h2 class="text-2xl font-bold title-font "><%= @quest.name %></h2>
                    </div>
                  </div>
                  <div class="py-4 flex flex-wrap md:flex-nowrap">
                    <div class="md:w-48 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                      <span class="font-semibold title-font">欲しい日</span>
                    </div>
                    <div class="md:flex-grow w-full">
                      <h2 class="text-xl font-medium title-font mb-2"><%= @quest.desired_date.present? ? l(@quest.desired_date, format: :short) : '記入なし' %></h2>
                    </div>
                  </div>
                  <div class="py-4 flex flex-wrap md:flex-nowrap">
                    <div class="md:w-48 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                      <span class="font-semibold title-font">備考</span>
                    </div>
                    <div class="md:flex-grow w-full">
                      <h2 class="text-xl font-medium title-font mb-2"><%= @quest.remarks.present? ? @quest.remarks : '記入なし' %></h2>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </dialog>

        <!-- Twitterシェア機能 -->
        <div class="tooltip tooltip-accent tooltip-bottom ml-4" data-tip="クエストクリアをシェアしよう！">
          <% twitter_url = "https://twitter.com/share?url=#{CGI.escape(request.base_url + quest_path(@quest))}&text=【#{CGI.escape(@quest.user.name)}さんのクエストに挑戦したよ！】%0a@sammy_study%20%23ギフトリクエスト%20%20%23テスト" %>
          <%= link_to twitter_url, title: 'Twitter', class: 'btn', target: '_blank', rel: 'noopener noreferrer' do %>
            <i class="fa-brands fa-x-twitter"></i> シェア
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= render 'caution_note' %>
    <!-- カードの外側 -->
    <div class="flex justify-center pt-4">
      <div class="btn btn-primary flex items-center">
        <%= image_tag 'quest.svg', alt: 'quest', class: "h-4" %>
        <%= link_to 'みんなのクエストへ', requests_path %>
      </div>
    </div>
</div>

app/views/quests/hint.html.erb
<div class="my-10 mx-auto w-11/12 sm:w-6/5 max-w-3xl">
  <div class="card w-full bg-base-100 image-full shadow-xl">
    <figure><%= image_tag 'note.webp', alt: 'ノートを読む' %></figure>
    <div class="card-body">
      <h2 class="card-title justify-center text-4xl font-moti">- Story3 -</h2>
        <div class="card w-full mx-auto bg-base-200 shadow-xl mt-4">
          <div class="flex flex-col md:flex-row items-center">
            <figure>
              <%= image_tag 'note.png', alt: 'Note', class: 'px-8 pt-8 md:pr-0 md:py-8 rounded-xl' %>
            </figure>
            <div class="card-body items-center text-left text-neutral font-poem">
              <h2 class="card-title"><%= @quest.title %></h2>
              <p class="text-sm"><%= @quest.quest %></p>
            </div>
          </div>
        </div>

      <div class="mt-4 sm:mt-8 sm:text-lg">う〜ん。もう少しで分かりそうなのに。<br>おや、ノートの隅に、詩を書くとき参考にしたと思われる走り書きがあるぞ。これを手がかりにできないだろうか？</div>
      <!-- ヒント -->
      <div class="flex justify-center gap-4 mt-4">
      <% @quest.hints.each do |hint| %>
        <button class="btn btn-ghost btn-sm w-1/4 border-neutral-300 text-neutral-300 hover:border-primary hover:text-primary" onclick="<%= hint.number %>.showModal()">手がかり<%= hint.number.gsub('hint', '') %></button>
        <dialog id="<%= hint.number %>" class="modal">
          <div class="modal-box">
            <h3 class="font-bold text-lg text-neutral-400">手がかり<%= hint.number.gsub('hint', '') %></h3>
            <p class="py-4 text-neutral-400 font-poem"><%= hint.content %></p>
          </div>
          <form method="dialog" class="modal-backdrop">
            <button>close</button>
          </form>
        </dialog>
      <% end %>
</div>

      <div class="mt-8 sm:text-lg text-base/7">
        今度こそ分かったぞ！<span class="text-accent"><%= @quest.user.name %></span>がいま欲しいと思っているのは──<br>
        （どれか1つ選択）
      </div>
      <!-- 選択肢 -->
      <div class="flex justify-center mt-4">
        <%= form_with url: answer_quest_path(@quest), method: :post, local: true, class: "bg-base-300/30 rounded-2xl" do |f| %>
          <div class="flex flex-col md:flex-row gap-1 flex-wrap">
            <% @quest.choices.each do |choice| %>
              <%= f.button choice.content, name: "selected_choice", value: choice.content, class: "btn m-1 md:m-2 hover:bg-primary hover:border-primary" %>
            <% end %>
          </div>
        <% end %>
      </div>
      
    </div>
  </div>
  <%= render 'caution_note' %>
</div>

app/views/quests/show.html.erb
<div class="my-10 mx-auto w-11/12 max-w-3xl">
  <div class="card w-full image-full shadow-xl">
    <figure><%= image_tag 'coffe.webp', alt: '喫茶店' %></figure>
    <div class="card-body">
      <h2 class="card-title justify-center text-4xl font-moti">- Story1 -</h2>

      <%= render 'story1', user_name: @quest.user.name %>

      <div class="card-actions justify-center mt-4">
        <%= link_to 'Story2へ', choice_quest_path(@quest), class: "btn btn-primary" %>
      </div>
    </div>
  </div>

  <%= render 'caution_note' %>

</div>