config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'
  resources :password_resets, only: %i[new create edit update]
  resources :users, only: %i[new create show]
  resource :profile, only: %i[show edit update]
  resources :requests
  resources :quests, only: [:show] do
    member do
      get :choice
      post :answer
      get :hint
      get :correct
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/_before_login_header.html.erb
<header class="bg-cyan-600/10">
  <div class="navbar">
    <div class="flex-1 px-4">
      <%= link_to '/' do %>
      <%= image_tag 'headerlogo.png', alt: 'logo_title', class: "h-14 w-auto max-w-full" %>
      <% end %>
    </div>
    <div class="flex-none flex items-center">
      <ul class="menu menu-horizontal px-1 flex items-center">
        <li><%= link_to 'ログイン', login_path %></li>
        <li><%= link_to '新規登録', new_user_path %></li>
        <li><%= link_to requests_path do %>
            <%= image_tag 'quest.svg', alt: 'quest', class: "h-9" %>
            <% end %>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-cyan-600/10"">
  <div class="container mx-auto py-4 px-5 flex flex-wrap justify-center items-center">
    <div class="flex justify-center items-center text-xs mb-4">
      <%= link_to '利用規約', "#", class: "mr-4 hover:text-accent" %>
      <%= link_to 'プライバシーポリシー', "#", class: "mr-4 hover:text-accent" %>
      <%= link_to 'お問合せ', "#", class: "hover:text-accent" %>
    </div>
    <p class="text-sm text-center w-full">©2024 ギフトリクエスト</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-cyan-600/10">
  <div class="navbar">
    <div class="flex-1 px-4">
      <%= link_to '/' do %>
      <%= image_tag 'headerlogo.png', alt: 'logo_title', class: "h-14 w-auto max-w-full" %>
      <% end %>
    </div>
    
    <div class="flex justify-end flex-1 px-2">
      <ul class="menu menu-horizontal flex items-center hidden sm:flex">
        <li>
          <%= link_to new_request_path do %>
          <%= image_tag 'create.svg', alt: 'create_quest', class: "h-9" %>
          <% end %>
        </li>
        <li>
          <%= link_to profile_path do %>
          <%= image_tag 'mypage.svg', alt: 'create_quest', class: "h-9" %>
          <% end %>
        </li>
      </ul>
      <div class="dropdown dropdown-end">
        <div tabindex="0" role="button" class="btn btn-ghost">
          <%= image_tag 'menu.svg', alt: 'menu', class: "h-7" %>
        </div>
        <ul tabindex="0" class="menu dropdown-content z-50 p-2 shadow bg-base-100 rounded-box w-52">
          <li>
            <div class="flex items-center">
              <%= image_tag 'create.svg', alt: 'create_quest', class: "h-4" %>
              <%= link_to 'リクエスト作成', new_request_path %>
            </div>
          </li>
          <li>
            <div class="flex items-center">
              <%= image_tag 'quest.svg', alt: 'quest', class: "h-4" %>
              <%= link_to 'みんなのクエスト', requests_path %>
            </div>
          </li>
          <li>
            <div class="flex items-center">
              <i class="fa-regular fa-circle-user"></i>
              <%= link_to 'マイページ', profile_path %>
            </div>
          </li>
          <li>
            <div class="flex items-center">
              <i class="fa-solid fa-right-from-bracket"></i>
              <%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete } %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>