config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'
  resources :password_resets, only: %i[new create edit update]
  resources :users, only: %i[new create show]
  resource :profile, only: %i[show edit update]
  resources :requests
  resources :quests, only: [:show] do
    member do
      get :choice
      post :answer
      get :hint
      get :correct
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :choices, dependent: :destroy
  has_many :hints, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }

  def hint_by_number(number)
    hints.find_by(number: number).content
  end

  def choice_by_number(number)
    choices.find_by(number: number).content
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  skip_before_action :require_login, only: %i[index show]
  before_action :set_token, only: %i[create]
  before_action :request_params, only: %i[create edit]
  before_action :set_request, only: %i[edit update destroy]

  def index
    @user_requests = Request.all.includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new
    @user_request = Request.new
  end

  def create
    @user_request = current_user.requests.build(request_params)
    service = CreateQuestService.new(@user_request, @api_key)
    if service.call
      redirect_to @user_request, notice: t('requests.create.success')
    else
      flash.now[:alert] = t('requests.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user_request = Request.find(params[:id])
  end

  def edit; end

  def update
    if @user_request.update(request_params)
      redirect_to @user_request, notice: t('users.update.success')
    else
      flash.now[:alert] = t('users.update.failure')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user_request.destroy!
    redirect_to requests_path, notice: 'クエストを削除しました', status: :see_other
  end

  private

  def set_request
    @user_request = current_user.requests.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:name, :remarks, :desired_date)
  end

  def set_token
    @api_key = Rails.application.credentials.dig(:openai, :api_key)
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_request.html.erb
<div class="w-full sm:w-1/2 md:w-1/2 lg:w-1/3 p-2">
     
  <div class="card bg-base-100 shadow-md">
    <div class="card-body flex items-left">
      <!-- Card content -->
      <div class="flex items-center space-x-4">
        <div class="">
          <% if user_request.user.avatar.attached? %>
            <%= link_to user_path(user_request.user) do %>
              <%= image_tag user_request.user.avatar.variant(:display), class: "rounded-full shadow-md h-20 w-20 object-cover min-w-20" %>
            <% end %>
          <% end %>
        </div>
        <!-- リンクパスを動的に変更 （本人のクエスト_リクエスト詳細、本人以外_クエスト挑戦） -->
        <% link_path = current_user == user_request.user ? request_path(user_request) : quest_path(user_request) %>
        <%= link_to link_path, class: "font-bold hover:text-accent" do %>
          <div class="mx-auto"> <!-- テキストを囲む追加のdiv、必要に応じて -->
            <p class="text-sm mb-2 line-clamp-2"><%= user_request.user.name %>さんのクエスト</p>
            <p class="text-xl"><%= user_request.title %></p>
          </div>
        <% end %>
      </div>

      <p class="mt-4">
        欲しい日: <%= user_request.desired_date.present? ? l(user_request.desired_date, format: :short) : '記入なし' %>
      </p>
      <div class="mt-2">
        <span class="bg-ash text-white text-sm font-medium py-1 px-3 rounded-full">タグ1</span>
        <span class="bg-ash text-white text-sm font-medium py-1 px-3 rounded-full">タグ2</span>
      </div>

      <!-- 削除機能 （本人のクエストの時のみ表示） -->
      <div class="flex justify-end items-center mt-2">
        <% if current_user && user_request.user_id == current_user.id %>
          <div class="mr-4">
            <%= link_to "削除", request_path(user_request), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？'}, class: "link link-hover hover:text-accent text-red-800" %>
          </div>
        <% end %>
        <div>
          <p>作成日: <%= l(user_request.created_at, format: :short) %></p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/requests/index.html.erb
<% content_for(:title, t('.title')) %>

  <div class="max-w-screen-xl mx-auto py-6 md:px-8">
    <div class="flex flex-col items-center justify-center my-8 mx-8">
      <h1 class="text-3xl md:text-4xl font-moti flex items-center mb-4">
        <%= image_tag 'quest.svg', alt: 'quest', class: "h-9 mr-2" %><%= t('.title') %>
      </h1>
      <p>みんなのクエストの中から、好きなクエストを選ぼう！タイトルをクリックすると、クエストが始まるよ。</p>
    </div>

    <% if @user_requests.present? %>
      <div class="flex flex-wrap">
         <%= render partial: 'requests/request', collection: @user_requests, as: :user_request %>
      </div>
    <% else %>
      <p>クエストはありません</p>
    <% end %>
  </div>
  <%= paginate @user_requests %>

app/views/requests/new.html.erb
<% content_for(:title, t('.title')) %>

<div class="hero min-h-screen bg-base-100 max-w-screen-lg mx-auto lg:rounded-xl">
    <div class="w-full px-8 md:px-0 max-w-md mx-auto">
      <h1 class="text-3xl md:text-4xl mb-5 text-center mb-8 font-moti"><%= t('.title') %></h1>
      <h1 class="mb-5 text-center mb-8">欲しいものを登録して、謎解きクエストを作ろう！</h1>
      <div class="mx-auto">
        <%= form_with model: @user_request, class: "space-y-4", local: true do |f| %>
          <div class="form-control mt-2">
            <%= f.label :name, class: "label-text mb-1" %>
            <%= f.text_field :name, class: "input input-bordered", placeholder:'例：クマのぬいぐるみ', required: true %>
          </div>
          <div class="form-control mt-2">
            <%= f.label :desired_date, class: "label-text mb-1" do %>
              <span class="border border-primary rounded-md text-xs p-0.5 text-primary mr-1">任意</span>欲しい日
            <% end %>
            <%= f.date_field :desired_date, class: "input input-bordered" %>
          </div>
          <div class="form-control mt-2">
            <%= f.label :remarks, class: "label-text mb-1" do %>
              <span class="border border-primary rounded-md text-xs p-0.5 text-primary mr-1">任意</span>備考
            <% end %>
            <%= f.text_area :remarks, class: "textarea textarea-bordered", placeholder:'例：抱きつけるような大きいもの' %>
          </div>
          <%= f.submit class: "btn btn-primary w-full" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/requests/show.html.erb
<% content_for(:title, t('.title')) %>

<div class="min-h-screen max-w-screen-lg shadow-xl bg-base-100 md:rounded-2xl p-8 mx-auto">
  <h1 class="text-3xl md:text-4xl font-moti text-center m-4 mt-8"><%= t('.title') %></h1>

  <section class="text-ash body-font">
    <div class="container px-8 pt-2 md:pt-8 mx-auto">
      <p class="mb-10 p-1 bg-gradient-to-r from-green-200 to-indigo-200 font-bold text-center rounded-full">リクエスト内容</p>
      <div class="-my-8 divide-y-4 divide-green-200 divide-dotted">
        <div class="py-4 flex flex-wrap md:flex-nowrap">
          <div class="md:w-48 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
            <span class="font-semibold title-font text-ash">欲しいもの</span>
          </div>
        <div class="md:flex-grow w-full">
          <h2 class="text-2xl font-bold title-font "><%= @user_request.name %></h2>
        </div>
        </div>
      <div class="py-4 flex flex-wrap md:flex-nowrap">
        <div class="md:w-48 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
          <span class="font-semibold title-font text-ash">欲しい日</span>
        </div>
        <div class="md:flex-grow w-full">
          <h2 class="text-xl font-medium title-font mb-2"><%= @user_request.desired_date.present? ? l(@user_request.desired_date, format: :short) : '記入なし' %></h2>
        </div>
      </div>
      <div class="py-4 flex flex-wrap md:flex-nowrap">
        <div class="md:w-48 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
          <span class="font-semibold title-font text-ash">備考</span>
        </div>
        <div class="md:flex-grow w-full">
          <h2 class="text-xl font-medium title-font mb-2"><%= @user_request.remarks.present? ? @user_request.remarks : '記入なし' %></h2>
        </div>
      </div>
    </div>
  </section>

  <section class="text-ash body-font">
    <div class="container px-8 py-8 mx-auto">
      <p class="mb-10 p-1 bg-gradient-to-r from-green-200 to-indigo-200 font-bold text-center rounded-full">クエスト内容</p>
      <div class="-my-8 divide-y-4 divide-green-200 divide-dotted">
        <div class="py-4 flex flex-wrap md:flex-nowrap">
          <div class="md:w-48 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
            <span class="font-semibold title-font text-ash">タイトル</span>
          </div>
        <div class="md:flex-grow w-full">
          <h2 class="text-2xl font-bold title-font "><%= @user_request.title %></h2>
        </div>
        </div>
      <div class="py-4 flex flex-wrap md:flex-nowrap">
        <div class="md:w-48 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
          <span class="font-semibold title-font text-ash">内容</span>
        </div>
        <div class="md:flex-grow w-full">
          <h2 class="text-xl font-medium title-font mb-2"><%= @user_request.quest %></h2>
        </div>
      </div>
      <div class="py-4 flex flex-wrap md:flex-nowrap">
        <div class="md:w-48 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
          <span class="font-semibold title-font text-ash">手がかり</span>
        </div>
        <div class="md:flex-grow w-full">
          <h2 class="text-xl font-medium title-font mb-2">
              <p>1.<%= @user_request.hint_by_number('hint1') %></p>
              <p>2.<%= @user_request.hint_by_number('hint2') %></p>
              <p>3.<%= @user_request.hint_by_number('hint3') %></p>
          </h2>
        </div>
      </div>
      <div class="py-4 flex flex-wrap md:flex-nowrap">
        <div class="md:w-48 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
          <span class="font-semibold title-font text-ash">選択肢</span>
        </div>
        <div class="md:flex-grow w-full">
          <h2 class="text-xl font-medium title-font mb-2">
              <p>1.<%= @user_request.choice_by_number('choice1') %></p>
              <p>2.<%= @user_request.choice_by_number('choice2') %></p>
              <p>3.<%= @user_request.choice_by_number('choice3') %></p>
          </h2>
        </div>
      </div>
    </div>
  </section>
  <!-- 詳細画面終わり -->
  <div class="md:pt-4">
    <div class="flex justify-center items-center flex-3 p-4 space-x-6">
      <!-- Twitterシェア機能 -->
      <div class="tooltip tooltip-accent tooltip-bottom " data-tip="クエストをシェアしよう♪">
        <% twitter_url = "https://twitter.com/share?url=#{CGI.escape(request.base_url + quest_path(@user_request))}&text=【「#{CGI.escape(@user_request.user.name)}」さんがクエストを作ったよ！挑戦してみてね！】%0a@sammy_study%20%23ギフトリクエスト%20%20%23テスト" %>
        <%= link_to twitter_url, title: 'Twitter', class: 'btn btn-neutral inline-flex items-center', target: '_blank', rel: 'noopener noreferrer' do %>
          <i class="fa-brands fa-x-twitter"></i> シェア
        <% end %>
      </div>
      <div>
        <%= link_to 'Myクエストに挑戦', quest_path(@user_request), class: "btn btn-primary inline-flex items-center" %>
      </div>
      <div>
        <%= link_to profile_path(current_user), class: "btn btn-primary inline-flex items-center" do %>
          <i class="fa-regular fa-circle-user"></i> マイページへ
        <% end %>
      </div>
      <% if current_user && @user_request.user_id == current_user.id %>
        <%= link_to request_path(@user_request), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？'} do %>
          <%= image_tag 'delete.svg', alt: 'delete_quest', class: "flex items-center justify-center h-9 hover:bg-gray-400 rounded-md transition-colors duration-150" %>
        <% end %>
      <% end %>
    </div>
      <p class="text-ash text-right">作成日: <%= l @user_request.created_at %></p>
  </div> 
</div> 