config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'
  resources :password_resets, only: %i[new create edit update]
  resources :users, only: %i[new create show]
  resource :profile, only: %i[show edit update]
  resources :requests
  resources :quests, only: [:show] do
    member do
      get :choice
      post :answer
      get :hint
      get :correct
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create guest_login]

  def new; end

  def create
    login(params[:email], params[:password]) do |user, failure|
      if user && !failure
        redirect_back_or_to(root_path, notice: t('user_sessions.create.success'))
      else
        case failure
        when :invalid_login
          flash.now[:alert] = t('errors.flash_messages.invalid_login')
        when :invalid_password
          flash.now[:alert] = t('errors.flash_messages.invalid_password')
        when :inactive
          flash.now[:alert] = t('errors.flash_messages.inactive')
        end
        render action: 'new', status: :unprocessable_entity

      end
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, flash: { info: t('user_sessions.destroy.success') }
  end

  def guest_login
    @guest_user = User.create(
    name: 'ゲスト',
    email: SecureRandom.alphanumeric(10) + "@email.com",
    password: 'password',
    password_confirmation: 'password'
    )
    auto_login(@guest_user)
    flash[:notice] = "ゲストとしてログインしました。再度ログインできないのでご注意ください。"
    redirect_to new_request_path
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>

<div class="hero min-h-screen bg-base-100 max-w-screen-lg mx-auto lg:rounded-xl">
  <div class="hero-content w-full flex-col lg:flex-row-reverse p-8">
    <div class="text-center lg:text-left lg:flex lg:items-center">
      <div class="lg:ml-4">
        <h1 class="text-4xl font-moti"><%= t('.title') %></h1>
        <p class="hidden lg:block py-4 text-sm">謎解きで繋がる、<br>心温まるギフト体験</p>
      </div>
      <div class="hidden lg:block lg:w-72">
        <%= image_tag 'bearbox.png', alt: 'bear&giftbox' %>
      </div>
    </div>

    <div class="card w-full max-w-md shadow-2xl bg-base-100">
      <%= form_with url: login_path, local: true do |f| %>
        <div class="card-body mx-auto">
          <div class="form-control mt-2">
            <%= f.label :email, class: "label-text" %>
            <%= f.email_field :email, placeholder: "email@example.com", class: "input input-bordered", required: true, autocomplete: "email" %>
          </div>
          <div class="form-control mt-2">
              <%= f.label :password, class: "label-text" %>
              <%= f.password_field :password, placeholder: "password", class: "input input-bordered", required: true, autocomplete: "current-password" %>
              <%= link_to t('user_sessions.new.password_forget'), new_password_reset_path, class: "label-text-alt link link-hover hover:text-accent mt-2" %>
          </div>
          <div class="form-control mt-4 lg:mt-6">
            <%= f.submit t('user_sessions.new.login'), class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>